#!/bin/bash
podman rm racnode3
podman create -t -i \
--hostname racnode3 \
--dns-search "example.info" \
--dns 172.20.1.250 \
--shm-size 4G \
--cpuset-cpus 0-1 \
--memory 16G \
--memory-swap 32G \
--sysctl kernel.shmall=2097152  \
--sysctl "kernel.sem=250 32000 100 128" \
--sysctl kernel.shmmax=8589934592  \
--sysctl kernel.shmmni=4096 \
--sysctl 'net.ipv4.conf.eth1.rp_filter=2' \
--health-cmd "/bin/python3 /opt/scripts/startup/scripts/main.py --checkracstatus" \
--cap-add=SYS_RESOURCE \
--cap-add=NET_ADMIN \
--cap-add=SYS_NICE \
--cap-add=AUDIT_WRITE \
--cap-add=AUDIT_CONTROL \
--cap-add=NET_RAW \
--secret pwdsecret \
--secret keysecret \
-e DNS_SERVERS="172.20.1.250" \
-e DB_SERVICE=service:soepdb \
-e CRS_PRIVATE_IP1=192.168.100.171 \
-e CRS_NODES="\"pubhost:racnode3,viphost:racnode3-vip\"" \
-e SCAN_NAME=racnodec1-scan \
-e INIT_SGA_SIZE=3G \
-e INIT_PGA_SIZE=2G \
-e DB_PWD_FILE=pwdsecret \
-e PWD_KEY=keysecret \
--device=/dev/sdb3:/dev/asm-disk1:rw \
-e CRS_ASM_DEVICE_LIST=/dev/asm-disk1 \
-e OP_TYPE=racaddnode \
-e EXISTING_CLS_NODE="racnode1,racnode2" \
-e INSTALL_NODE=racnode3 \
-e DB_NAME=orcl \
-e ORACLE_PDB_NAME=PDB \
-p 7046:22 \
--restart=always \
--ulimit rtprio=99 \
--systemd=always \
--name racnode3 \
phx.ocir.io/intsanjaysingh/oracle/database-rac:19.25.0-final

podman network disconnect podman racnode3
podman network connect rac_pub1_nw --ip 172.20.1.172 racnode3
podman network connect rac_priv1_nw --ip 192.168.100.172  racnode3
podman start racnode3
sleep 60
podman exec racnode3 /bin/bash -c "tail -f /tmp/orod/oracle_rac_setup.log"
